import asyncio
import re
from sqlalchemy import select, and_, func
from prometheus_client import Counter

from src.database.session import async_session_maker
from src.database.models import UserSurvey, DatingMatch, User
from src.services.rabbit import send_to_queue
from src.bot.keyboards.dating import get_dating_kb

# --- OBSERVABILITY ---
from src.utils.logger import logger
from src.utils.alerting import send_alert

# Метрика
MATCHES_GENERATED = Counter('rex_dating_matches_total', 'Total matches generated by algorithm')

def _normalize_list(data):
    """Превращает строку 'Бег, Зал' или список ['Бег', 'Зал'] в set({'бег', 'зал'})."""
    if not data:
        return set()
    if isinstance(data, list):
        return set(str(x).lower().strip() for x in data)
    if isinstance(data, str):
        return set(x.lower().strip() for x in data.split(','))
    return set()

def _parse_int(value, default=0):
    """Безопасно извлекает число из строки (например '25 лет' -> 25)."""
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        # Ищем все цифры
        nums = re.findall(r'\d+', value)
        if nums:
            return int(nums[0])
    return default

async def run_daily_matching():
    """
    Интеллектуальный алгоритм подбора пар.
    Учитывает город, пол, возраст и пересечение по видам спорта.
    """
    log = logger.bind(task="dating_matching")
    log.info("matching_started")
    
    try:
        async with async_session_maker() as session:
            # 1. Берем всех АКТИВНЫХ пользователей, которые ищут пару
            stmt_users = select(UserSurvey).join(User).where(
                and_(
                    UserSurvey.mode == 'dating',
                    User.subscription_expires_at > func.now()
                )
            )
            result = await session.execute(stmt_users)
            seekers = result.scalars().all()
            
            log.info("profiles_fetched", count=len(seekers))
            matches_count = 0

            for me in seekers:
                try:
                    my_id = me.user_id
                    my_data = me.answers or {}
                    
                    # --- Извлекаем предпочтения Ищущего ---
                    my_city = str(my_data.get('city', '')).strip().lower()
                    my_gender = str(my_data.get('gender', '')).lower() # Мой пол
                    
                    # Кого ищу? (Если в анкете есть partner_pref_gender, берем его, иначе простая логика М<->Ж)
                    # Предполагаем, что в анкете есть поля: partner_gender, partner_age_min, partner_age_max
                    pref_gender = str(my_data.get('partner_gender', '')).lower()
                    if not pref_gender or pref_gender == 'любой':
                        # Фолбэк: М ищет Ж, Ж ищет М
                        pref_gender = 'женский' if 'муж' in my_gender else 'мужской'

                    pref_age_min = _parse_int(my_data.get('partner_age_min'), 18)
                    pref_age_max = _parse_int(my_data.get('partner_age_max'), 99)
                    
                    # Мои виды спорта (для поиска пересечений)
                    my_sports = _normalize_list(my_data.get('sports'))

                    # --- Поиск Кандидатов ---
                    
                    # Кого я уже видел?
                    subq_seen = select(DatingMatch.target_user_id).where(DatingMatch.user_id == my_id)
                    
                    # Запрашиваем батч потенциальных кандидатов (чтобы не тянуть всю базу)
                    # Фильтруем на уровне SQL самое простое: режим + подписка + не видел + не я сам
                    stmt_candidates = select(UserSurvey).join(User).where(
                        and_(
                            UserSurvey.mode == 'dating',
                            User.subscription_expires_at > func.now(),
                            UserSurvey.user_id != my_id,
                            UserSurvey.user_id.not_in(subq_seen)
                        )
                    ).limit(50) # Берем 50 ближайших, фильтруем питоном
                    
                    candidates_res = await session.execute(stmt_candidates)
                    candidates = candidates_res.scalars().all()
                    
                    best_match = None
                    
                    for cand in candidates:
                        cand_data = cand.answers or {}
                        
                        # 1. Город (Строгое совпадение)
                        cand_city = str(cand_data.get('city', '')).strip().lower()
                        if my_city and cand_city and my_city not in cand_city and cand_city not in my_city:
                            continue # Не тот город

                        # 2. Пол (Строгое совпадение)
                        cand_gender = str(cand_data.get('gender', '')).lower()
                        if pref_gender and pref_gender not in cand_gender:
                            continue

                        # 3. Возраст (Диапазон)
                        cand_age = _parse_int(cand_data.get('age'))
                        if not (pref_age_min <= cand_age <= pref_age_max):
                            continue

                        # 4. Спорт (Есть ли хоть одно совпадение?)
                        # Если пользователь не указал спорт, считаем что ему всё равно
                        cand_sports = _normalize_list(cand_data.get('sports'))
                        if my_sports and cand_sports:
                            # Проверяем пересечение множеств (intersection)
                            if not (my_sports & cand_sports):
                                continue # Нет общих интересов

                        # Если дошли сюда — кандидат подходит!
                        best_match = cand
                        break # Нашли одного, хватит
                    
                    if not best_match:
                        continue # Нет подходящих пар сегодня

                    # --- Отправка Анкеты ---
                    cand_data = best_match.answers or {}
                    
                    # Формируем красивый текст
                    # Имя, Возраст | Вид спорта | Уровень
                    info_line = f"{cand_data.get('name', 'Аноним')}, {cand_data.get('age', '??')}"
                    
                    sports_str = ", ".join(cand_data.get('sports', '').split(',')) if isinstance(cand_data.get('sports'), str) else "Спорт"
                    level = cand_data.get('level', 'Любитель')
                    
                    caption = (
                        f"🎯 <b>Вам подобрана пара!</b>\n\n"
                        f"👤 <b>{info_line}</b>\n"
                        f"📍 {cand_data.get('city', 'Город')}\n"
                        f"🏅 {sports_str} ({level})\n\n"
                        f"ℹ️ {cand_data.get('about', '')}"
                    )
                    
                    msg_data = {
                        "user_id": my_id,
                        "text": caption,
                        "photo": cand_data.get('photo'),
                        "keyboard": get_dating_kb(best_match.user_id).model_dump()
                    }
                    
                    await send_to_queue("q_notifications", msg_data)
                    
                    MATCHES_GENERATED.inc()
                    matches_count += 1
                    
                    await asyncio.sleep(0.05)

                except Exception as loop_e:
                    log.error("error_processing_user", user_id=me.user_id, error=str(loop_e))
                    continue

            log.info("matching_completed", matches_created=matches_count)

    except Exception as e:
        log.error("matching_critical_failure", error=str(e))
        await send_alert(e, context="Dating Matching Service")
        raise e